---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "appdb-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "appdb"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.appdb.appdb_password }}"
type: "Opaque"
