---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__cache: "cache-service:6379,password={{ .Values.secrets.api.cache_password }}"
  CACHE_PASSWORD: "{{ .Values.secrets.api.cache_password }}"
  CACHE_URI: "redis://:{{ .Values.secrets.api.cache_password }}@cache-service:6379"
  ConnectionStrings__appdb: "Host=appdb-service;Port=5432;Username=postgres;Password={{ .Values.secrets.api.appdb_password }}"
  APPDB_PASSWORD: "{{ .Values.secrets.api.appdb_password }}"
  APPDB_URI: "postgresql://postgres:{{ .Values.secrets.api.appdb_password }}@appdb-service:5432"
type: "Opaque"
