<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="assets/**/*" />
    <None Include="docs/**/*" />
    <None Include=".config/**/*" />
    <None Include=".template.config/**/*" />
    
    <None Include="*.yaml" />
    <None Include=".bun-version" />
    <None Include=".dockerignore" />
    <None Include=".editorconfig" />
    <None Include=".globalconfig" />
    <None Include="LICENSE" />
  </ItemGroup>
  
</Project>
