parameters:
  api:
    port_http: 8080
    api_image: "api:latest"
secrets:
  cache:
    cache_password: ""
  appdb:
    appdb_password: ""
  api:
    ConnectionStrings__cache: ""
    cache_password: ""
    CACHE_URI: ""
    ConnectionStrings__appdb: ""
    appdb_password: ""
    APPDB_URI: ""
config:
  appdb:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_USER: "postgres"
  api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    ASPNETCORE_ENVIRONMENT: "Production"
    CACHE_HOST: "cache-service"
    CACHE_PORT: "6379"
    APPDB_HOST: "appdb-service"
    APPDB_PORT: "5432"
    APPDB_USERNAME: "postgres"
    APPDB_JDBCCONNECTIONSTRING: "jdbc:postgresql://appdb-service:5432"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://homelab-dashboard-service:18889"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_SERVICE_NAME: "api"
