<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>44de2c33-3e4c-4063-b83b-bcdbd04778f7</UserSecretsId>
    <IsPackable>false</IsPackable>
    <IsPublishable>true</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Kubernetes" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.Redis" />
    <PackageReference Include="MessagePack" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Api/Template.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Update="MessagePackAnalyzer" Version="3.1.7" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="MessagePackAnalyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
