apiVersion: "v2"
name: "my-template-app"
version: "1.0.0"
kubeVersion: ">= 1.18.0-0"
description: "My template application deployed to Kubernetes"
type: "application"
keywords:
  - "aspire"
  - "kubernetes"
appVersion: "1.0.0"
deprecated: false
