// <auto-generated/>
#nullable enable

{{~ if namespace ~}}
namespace {{ namespace }}
{
{{~ end ~}}
    [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct, AllowMultiple = false)]
    public sealed class GenerateIdAttribute : System.Attribute
    {
        public GenerateIdAttribute() { }
        public GenerateIdAttribute(System.Type underlyingType) { }
    }
{{~ if namespace ~}}
}
{{~ end ~}}
