<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoWarn>S3904</NoWarn>
  </PropertyGroup>

  <ItemGroup Label="Include your files as content">
    <Content Include="../**/*.*" />
  </ItemGroup>
  
  <ItemGroup Label="Exclude build output and source files">
    <Content Remove="../artifacts/**" />
    <Content Remove="../bin/**" />
    <Content Remove="../obj/**" />
    <Content Remove="../src/**" />
    <Content Remove="../test/**" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageVersion Update="MessagePackAnalyzer" Version="3.1.7" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Update="MessagePackAnalyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
</Project>
