name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5

      - name: Restore
        run: dotnet restore

      - name: Run unit tests
        run: dotnet test --configuration Release --no-restore
